import assert from "node:assert"

type Trie = {
  value: string
  children: Trie[]
  indices?: number[]
}

function _insert(trie: Trie, words: string[], index: number) {
  const word = words[index]
  let current = trie
  for (let i = 0; i < word.length; i++) {
    let child = current.children.find((c) => c.value == word[i])
    if (!child) {
      child = { value: word[i], children: [] }
      current.children.push(child)
    }
    current = child
  }

  if (!current.indices) current.indices = []
  current.indices.push(index)
}

function _buildTrie(words: string[]): Trie {
  const result: Trie = { value: "", children: [] }
  for (let i = 0; i < words.length; i++) {
    _insert(result, words, i)
  }
  return result
}

function _findAt(
  board: string[][],
  trie: Trie,
  r: number,
  c: number,
  visited: boolean[][],
): number[] {
  if (visited[r][c] || trie.value != board[r][c]) return []

  visited[r][c] = true
  const result: number[] = []

  if (trie.indices) result.push(...trie.indices)

  if (r - 1 >= 0) {
    trie.children.forEach((child) =>
      result.push(..._findAt(board, child, r - 1, c, visited)),
    )
  }
  if (c + 1 < board[0].length) {
    trie.children.forEach((child) =>
      result.push(..._findAt(board, child, r, c + 1, visited)),
    )
  }
  if (r + 1 < board.length) {
    trie.children.forEach((child) =>
      result.push(..._findAt(board, child, r + 1, c, visited)),
    )
  }
  if (c - 1 >= 0) {
    trie.children.forEach((child) =>
      result.push(..._findAt(board, child, r, c - 1, visited)),
    )
  }

  visited[r][c] = false
  return result
}

function _find(board: string[][], trie: Trie): number[] {
  const visited: boolean[][] = Array.from({ length: board.length }, () =>
    Array.from({ length: board[0].length }, () => false),
  )
  const result: number[] = []
  for (let r = 0; r < board.length; r++)
  for (let c = 0; c < board[0].length; c++) {
    for (const child of trie.children) {
      result.push(..._findAt(board, child, r, c, visited))
    }
  }
  return result
}

function findWords(board: string[][], words: string[]): string[] {
  const trie = _buildTrie(words)
  const indices = _find(board, trie)
  const uniqueIndices = Array.from(new Set(indices))
  return uniqueIndices.map((index) => words[index]).sort()
}

assert.deepEqual(
  findWords(
    [
      ["o", "a", "a", "n"],
      ["e", "t", "a", "e"],
      ["i", "h", "k", "r"],
      ["i", "f", "l", "v"],
    ],
    ["oath", "pea", "eat", "rain"],
  ),
  ["eat", "oath"],
)
assert.deepEqual(
  findWords(
    [
      ["a", "b"],
      ["c", "d"],
    ],
    ["abcb"],
  ),
  [],
)
assert.deepEqual(
  findWords(
    [
      ["m", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"],
      ["n", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["o", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["p", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["q", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["r", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["s", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["t", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["u", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["v", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["w", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
      ["x", "y", "z", "a", "a", "a", "a", "a", "a", "a", "a", "a"],
    ],
    [
      "aaaaaaaaaa",
      "aaaaaaaaab",
      "aaaaaaaaac",
      "aaaaaaaaad",
      "aaaaaaaaae",
      "aaaaaaaaaf",
      "aaaaaaaaag",
      "aaaaaaaaah",
      "aaaaaaaaai",
      "aaaaaaaaaj",
      "aaaaaaaaak",
      "aaaaaaaaal",
      "aaaaaaaaam",
      "aaaaaaaaan",
      "aaaaaaaaao",
      "aaaaaaaaap",
      "aaaaaaaaaq",
      "aaaaaaaaar",
      "aaaaaaaaas",
      "aaaaaaaaat",
      "aaaaaaaaau",
      "aaaaaaaaav",
      "aaaaaaaaaw",
      "aaaaaaaaax",
      "aaaaaaaaay",
      "aaaaaaaaaz",
      "aaaaaaaaba",
      "aaaaaaaabb",
      "aaaaaaaabc",
      "aaaaaaaabd",
      "aaaaaaaabe",
      "aaaaaaaabf",
      "aaaaaaaabg",
      "aaaaaaaabh",
      "aaaaaaaabi",
      "aaaaaaaabj",
      "aaaaaaaabk",
      "aaaaaaaabl",
      "aaaaaaaabm",
      "aaaaaaaabn",
      "aaaaaaaabo",
      "aaaaaaaabp",
      "aaaaaaaabq",
      "aaaaaaaabr",
      "aaaaaaaabs",
      "aaaaaaaabt",
      "aaaaaaaabu",
      "aaaaaaaabv",
      "aaaaaaaabw",
      "aaaaaaaabx",
      "aaaaaaaaby",
      "aaaaaaaabz",
      "aaaaaaaaca",
      "aaaaaaaacb",
      "aaaaaaaacc",
      "aaaaaaaacd",
      "aaaaaaaace",
      "aaaaaaaacf",
      "aaaaaaaacg",
      "aaaaaaaach",
      "aaaaaaaaci",
      "aaaaaaaacj",
      "aaaaaaaack",
      "aaaaaaaacl",
      "aaaaaaaacm",
      "aaaaaaaacn",
      "aaaaaaaaco",
      "aaaaaaaacp",
      "aaaaaaaacq",
      "aaaaaaaacr",
      "aaaaaaaacs",
      "aaaaaaaact",
      "aaaaaaaacu",
      "aaaaaaaacv",
      "aaaaaaaacw",
      "aaaaaaaacx",
      "aaaaaaaacy",
      "aaaaaaaacz",
      "aaaaaaaada",
      "aaaaaaaadb",
      "aaaaaaaadc",
      "aaaaaaaadd",
      "aaaaaaaade",
      "aaaaaaaadf",
      "aaaaaaaadg",
      "aaaaaaaadh",
      "aaaaaaaadi",
      "aaaaaaaadj",
      "aaaaaaaadk",
      "aaaaaaaadl",
      "aaaaaaaadm",
      "aaaaaaaadn",
      "aaaaaaaado",
      "aaaaaaaadp",
      "aaaaaaaadq",
      "aaaaaaaadr",
      "aaaaaaaads",
      "aaaaaaaadt",
      "aaaaaaaadu",
      "aaaaaaaadv",
      "aaaaaaaadw",
      "aaaaaaaadx",
      "aaaaaaaady",
      "aaaaaaaadz",
      "aaaaaaaaea",
      "aaaaaaaaeb",
      "aaaaaaaaec",
      "aaaaaaaaed",
      "aaaaaaaaee",
      "aaaaaaaaef",
      "aaaaaaaaeg",
      "aaaaaaaaeh",
      "aaaaaaaaei",
      "aaaaaaaaej",
      "aaaaaaaaek",
      "aaaaaaaael",
      "aaaaaaaaem",
      "aaaaaaaaen",
      "aaaaaaaaeo",
      "aaaaaaaaep",
      "aaaaaaaaeq",
      "aaaaaaaaer",
      "aaaaaaaaes",
      "aaaaaaaaet",
      "aaaaaaaaeu",
      "aaaaaaaaev",
      "aaaaaaaaew",
      "aaaaaaaaex",
      "aaaaaaaaey",
      "aaaaaaaaez",
      "aaaaaaaafa",
      "aaaaaaaafb",
      "aaaaaaaafc",
      "aaaaaaaafd",
      "aaaaaaaafe",
      "aaaaaaaaff",
      "aaaaaaaafg",
      "aaaaaaaafh",
      "aaaaaaaafi",
      "aaaaaaaafj",
      "aaaaaaaafk",
      "aaaaaaaafl",
      "aaaaaaaafm",
      "aaaaaaaafn",
      "aaaaaaaafo",
      "aaaaaaaafp",
      "aaaaaaaafq",
      "aaaaaaaafr",
      "aaaaaaaafs",
      "aaaaaaaaft",
      "aaaaaaaafu",
      "aaaaaaaafv",
      "aaaaaaaafw",
      "aaaaaaaafx",
      "aaaaaaaafy",
      "aaaaaaaafz",
      "aaaaaaaaga",
      "aaaaaaaagb",
      "aaaaaaaagc",
      "aaaaaaaagd",
      "aaaaaaaage",
      "aaaaaaaagf",
      "aaaaaaaagg",
      "aaaaaaaagh",
      "aaaaaaaagi",
      "aaaaaaaagj",
      "aaaaaaaagk",
      "aaaaaaaagl",
      "aaaaaaaagm",
      "aaaaaaaagn",
      "aaaaaaaago",
      "aaaaaaaagp",
      "aaaaaaaagq",
      "aaaaaaaagr",
      "aaaaaaaags",
      "aaaaaaaagt",
      "aaaaaaaagu",
      "aaaaaaaagv",
      "aaaaaaaagw",
      "aaaaaaaagx",
      "aaaaaaaagy",
      "aaaaaaaagz",
      "aaaaaaaaha",
      "aaaaaaaahb",
      "aaaaaaaahc",
      "aaaaaaaahd",
      "aaaaaaaahe",
      "aaaaaaaahf",
      "aaaaaaaahg",
      "aaaaaaaahh",
      "aaaaaaaahi",
      "aaaaaaaahj",
      "aaaaaaaahk",
      "aaaaaaaahl",
      "aaaaaaaahm",
      "aaaaaaaahn",
      "aaaaaaaaho",
      "aaaaaaaahp",
      "aaaaaaaahq",
      "aaaaaaaahr",
      "aaaaaaaahs",
      "aaaaaaaaht",
      "aaaaaaaahu",
      "aaaaaaaahv",
      "aaaaaaaahw",
      "aaaaaaaahx",
      "aaaaaaaahy",
      "aaaaaaaahz",
      "aaaaaaaaia",
      "aaaaaaaaib",
      "aaaaaaaaic",
      "aaaaaaaaid",
      "aaaaaaaaie",
      "aaaaaaaaif",
      "aaaaaaaaig",
      "aaaaaaaaih",
      "aaaaaaaaii",
      "aaaaaaaaij",
      "aaaaaaaaik",
      "aaaaaaaail",
      "aaaaaaaaim",
      "aaaaaaaain",
      "aaaaaaaaio",
      "aaaaaaaaip",
      "aaaaaaaaiq",
      "aaaaaaaair",
      "aaaaaaaais",
      "aaaaaaaait",
      "aaaaaaaaiu",
      "aaaaaaaaiv",
      "aaaaaaaaiw",
      "aaaaaaaaix",
      "aaaaaaaaiy",
      "aaaaaaaaiz",
      "aaaaaaaaja",
      "aaaaaaaajb",
      "aaaaaaaajc",
      "aaaaaaaajd",
      "aaaaaaaaje",
      "aaaaaaaajf",
      "aaaaaaaajg",
      "aaaaaaaajh",
      "aaaaaaaaji",
      "aaaaaaaajj",
      "aaaaaaaajk",
      "aaaaaaaajl",
      "aaaaaaaajm",
      "aaaaaaaajn",
      "aaaaaaaajo",
      "aaaaaaaajp",
      "aaaaaaaajq",
      "aaaaaaaajr",
      "aaaaaaaajs",
      "aaaaaaaajt",
      "aaaaaaaaju",
      "aaaaaaaajv",
      "aaaaaaaajw",
      "aaaaaaaajx",
      "aaaaaaaajy",
      "aaaaaaaajz",
      "aaaaaaaaka",
      "aaaaaaaakb",
      "aaaaaaaakc",
      "aaaaaaaakd",
      "aaaaaaaake",
      "aaaaaaaakf",
      "aaaaaaaakg",
      "aaaaaaaakh",
      "aaaaaaaaki",
      "aaaaaaaakj",
      "aaaaaaaakk",
      "aaaaaaaakl",
      "aaaaaaaakm",
      "aaaaaaaakn",
      "aaaaaaaako",
      "aaaaaaaakp",
      "aaaaaaaakq",
      "aaaaaaaakr",
      "aaaaaaaaks",
      "aaaaaaaakt",
      "aaaaaaaaku",
      "aaaaaaaakv",
      "aaaaaaaakw",
      "aaaaaaaakx",
      "aaaaaaaaky",
      "aaaaaaaakz",
      "aaaaaaaala",
      "aaaaaaaalb",
      "aaaaaaaalc",
      "aaaaaaaald",
      "aaaaaaaale",
      "aaaaaaaalf",
      "aaaaaaaalg",
      "aaaaaaaalh",
      "aaaaaaaali",
      "aaaaaaaalj",
      "aaaaaaaalk",
      "aaaaaaaall",
      "aaaaaaaalm",
      "aaaaaaaaln",
      "aaaaaaaalo",
      "aaaaaaaalp",
      "aaaaaaaalq",
      "aaaaaaaalr",
      "aaaaaaaals",
      "aaaaaaaalt",
      "aaaaaaaalu",
      "aaaaaaaalv",
      "aaaaaaaalw",
      "aaaaaaaalx",
      "aaaaaaaaly",
      "aaaaaaaalz",
      "aaaaaaaama",
      "aaaaaaaamb",
      "aaaaaaaamc",
      "aaaaaaaamd",
      "aaaaaaaame",
      "aaaaaaaamf",
      "aaaaaaaamg",
      "aaaaaaaamh",
      "aaaaaaaami",
      "aaaaaaaamj",
      "aaaaaaaamk",
      "aaaaaaaaml",
      "aaaaaaaamm",
      "aaaaaaaamn",
      "aaaaaaaamo",
      "aaaaaaaamp",
      "aaaaaaaamq",
      "aaaaaaaamr",
      "aaaaaaaams",
      "aaaaaaaamt",
      "aaaaaaaamu",
      "aaaaaaaamv",
      "aaaaaaaamw",
      "aaaaaaaamx",
      "aaaaaaaamy",
      "aaaaaaaamz",
      "aaaaaaaana",
      "aaaaaaaanb",
      "aaaaaaaanc",
      "aaaaaaaand",
      "aaaaaaaane",
      "aaaaaaaanf",
      "aaaaaaaang",
      "aaaaaaaanh",
      "aaaaaaaani",
      "aaaaaaaanj",
      "aaaaaaaank",
      "aaaaaaaanl",
      "aaaaaaaanm",
      "aaaaaaaann",
      "aaaaaaaano",
      "aaaaaaaanp",
      "aaaaaaaanq",
      "aaaaaaaanr",
      "aaaaaaaans",
      "aaaaaaaant",
      "aaaaaaaanu",
      "aaaaaaaanv",
      "aaaaaaaanw",
      "aaaaaaaanx",
      "aaaaaaaany",
      "aaaaaaaanz",
      "aaaaaaaaoa",
      "aaaaaaaaob",
      "aaaaaaaaoc",
      "aaaaaaaaod",
      "aaaaaaaaoe",
      "aaaaaaaaof",
      "aaaaaaaaog",
      "aaaaaaaaoh",
      "aaaaaaaaoi",
      "aaaaaaaaoj",
      "aaaaaaaaok",
      "aaaaaaaaol",
      "aaaaaaaaom",
      "aaaaaaaaon",
      "aaaaaaaaoo",
      "aaaaaaaaop",
      "aaaaaaaaoq",
      "aaaaaaaaor",
      "aaaaaaaaos",
      "aaaaaaaaot",
      "aaaaaaaaou",
      "aaaaaaaaov",
      "aaaaaaaaow",
      "aaaaaaaaox",
      "aaaaaaaaoy",
      "aaaaaaaaoz",
      "aaaaaaaapa",
      "aaaaaaaapb",
      "aaaaaaaapc",
      "aaaaaaaapd",
      "aaaaaaaape",
      "aaaaaaaapf",
      "aaaaaaaapg",
      "aaaaaaaaph",
      "aaaaaaaapi",
      "aaaaaaaapj",
      "aaaaaaaapk",
      "aaaaaaaapl",
      "aaaaaaaapm",
      "aaaaaaaapn",
      "aaaaaaaapo",
      "aaaaaaaapp",
      "aaaaaaaapq",
      "aaaaaaaapr",
      "aaaaaaaaps",
      "aaaaaaaapt",
      "aaaaaaaapu",
      "aaaaaaaapv",
      "aaaaaaaapw",
      "aaaaaaaapx",
      "aaaaaaaapy",
      "aaaaaaaapz",
      "aaaaaaaaqa",
      "aaaaaaaaqb",
      "aaaaaaaaqc",
      "aaaaaaaaqd",
      "aaaaaaaaqe",
      "aaaaaaaaqf",
      "aaaaaaaaqg",
      "aaaaaaaaqh",
      "aaaaaaaaqi",
      "aaaaaaaaqj",
      "aaaaaaaaqk",
      "aaaaaaaaql",
      "aaaaaaaaqm",
      "aaaaaaaaqn",
      "aaaaaaaaqo",
      "aaaaaaaaqp",
      "aaaaaaaaqq",
      "aaaaaaaaqr",
      "aaaaaaaaqs",
      "aaaaaaaaqt",
      "aaaaaaaaqu",
      "aaaaaaaaqv",
      "aaaaaaaaqw",
      "aaaaaaaaqx",
      "aaaaaaaaqy",
      "aaaaaaaaqz",
      "aaaaaaaara",
      "aaaaaaaarb",
      "aaaaaaaarc",
      "aaaaaaaard",
      "aaaaaaaare",
      "aaaaaaaarf",
      "aaaaaaaarg",
      "aaaaaaaarh",
      "aaaaaaaari",
      "aaaaaaaarj",
      "aaaaaaaark",
      "aaaaaaaarl",
      "aaaaaaaarm",
      "aaaaaaaarn",
      "aaaaaaaaro",
      "aaaaaaaarp",
      "aaaaaaaarq",
      "aaaaaaaarr",
      "aaaaaaaars",
      "aaaaaaaart",
      "aaaaaaaaru",
      "aaaaaaaarv",
      "aaaaaaaarw",
      "aaaaaaaarx",
      "aaaaaaaary",
      "aaaaaaaarz",
      "aaaaaaaasa",
      "aaaaaaaasb",
      "aaaaaaaasc",
      "aaaaaaaasd",
      "aaaaaaaase",
      "aaaaaaaasf",
      "aaaaaaaasg",
      "aaaaaaaash",
      "aaaaaaaasi",
      "aaaaaaaasj",
      "aaaaaaaask",
      "aaaaaaaasl",
      "aaaaaaaasm",
      "aaaaaaaasn",
      "aaaaaaaaso",
      "aaaaaaaasp",
      "aaaaaaaasq",
      "aaaaaaaasr",
      "aaaaaaaass",
      "aaaaaaaast",
      "aaaaaaaasu",
      "aaaaaaaasv",
      "aaaaaaaasw",
      "aaaaaaaasx",
      "aaaaaaaasy",
      "aaaaaaaasz",
      "aaaaaaaata",
      "aaaaaaaatb",
      "aaaaaaaatc",
      "aaaaaaaatd",
      "aaaaaaaate",
      "aaaaaaaatf",
      "aaaaaaaatg",
      "aaaaaaaath",
      "aaaaaaaati",
      "aaaaaaaatj",
      "aaaaaaaatk",
      "aaaaaaaatl",
      "aaaaaaaatm",
      "aaaaaaaatn",
      "aaaaaaaato",
      "aaaaaaaatp",
      "aaaaaaaatq",
      "aaaaaaaatr",
      "aaaaaaaats",
      "aaaaaaaatt",
      "aaaaaaaatu",
      "aaaaaaaatv",
      "aaaaaaaatw",
      "aaaaaaaatx",
      "aaaaaaaaty",
      "aaaaaaaatz",
      "aaaaaaaaua",
      "aaaaaaaaub",
      "aaaaaaaauc",
      "aaaaaaaaud",
      "aaaaaaaaue",
      "aaaaaaaauf",
      "aaaaaaaaug",
      "aaaaaaaauh",
      "aaaaaaaaui",
      "aaaaaaaauj",
      "aaaaaaaauk",
      "aaaaaaaaul",
      "aaaaaaaaum",
      "aaaaaaaaun",
      "aaaaaaaauo",
      "aaaaaaaaup",
      "aaaaaaaauq",
      "aaaaaaaaur",
      "aaaaaaaaus",
      "aaaaaaaaut",
      "aaaaaaaauu",
      "aaaaaaaauv",
      "aaaaaaaauw",
      "aaaaaaaaux",
      "aaaaaaaauy",
      "aaaaaaaauz",
      "aaaaaaaava",
      "aaaaaaaavb",
      "aaaaaaaavc",
      "aaaaaaaavd",
      "aaaaaaaave",
      "aaaaaaaavf",
      "aaaaaaaavg",
      "aaaaaaaavh",
      "aaaaaaaavi",
      "aaaaaaaavj",
      "aaaaaaaavk",
      "aaaaaaaavl",
      "aaaaaaaavm",
      "aaaaaaaavn",
      "aaaaaaaavo",
      "aaaaaaaavp",
      "aaaaaaaavq",
      "aaaaaaaavr",
      "aaaaaaaavs",
      "aaaaaaaavt",
      "aaaaaaaavu",
      "aaaaaaaavv",
      "aaaaaaaavw",
      "aaaaaaaavx",
      "aaaaaaaavy",
      "aaaaaaaavz",
      "aaaaaaaawa",
      "aaaaaaaawb",
      "aaaaaaaawc",
      "aaaaaaaawd",
      "aaaaaaaawe",
      "aaaaaaaawf",
      "aaaaaaaawg",
      "aaaaaaaawh",
      "aaaaaaaawi",
      "aaaaaaaawj",
      "aaaaaaaawk",
      "aaaaaaaawl",
      "aaaaaaaawm",
      "aaaaaaaawn",
      "aaaaaaaawo",
      "aaaaaaaawp",
      "aaaaaaaawq",
      "aaaaaaaawr",
      "aaaaaaaaws",
      "aaaaaaaawt",
      "aaaaaaaawu",
      "aaaaaaaawv",
      "aaaaaaaaww",
      "aaaaaaaawx",
      "aaaaaaaawy",
      "aaaaaaaawz",
      "aaaaaaaaxa",
      "aaaaaaaaxb",
      "aaaaaaaaxc",
      "aaaaaaaaxd",
      "aaaaaaaaxe",
      "aaaaaaaaxf",
      "aaaaaaaaxg",
      "aaaaaaaaxh",
      "aaaaaaaaxi",
      "aaaaaaaaxj",
      "aaaaaaaaxk",
      "aaaaaaaaxl",
      "aaaaaaaaxm",
      "aaaaaaaaxn",
      "aaaaaaaaxo",
      "aaaaaaaaxp",
      "aaaaaaaaxq",
      "aaaaaaaaxr",
      "aaaaaaaaxs",
      "aaaaaaaaxt",
      "aaaaaaaaxu",
      "aaaaaaaaxv",
      "aaaaaaaaxw",
      "aaaaaaaaxx",
      "aaaaaaaaxy",
      "aaaaaaaaxz",
      "aaaaaaaaya",
      "aaaaaaaayb",
      "aaaaaaaayc",
      "aaaaaaaayd",
      "aaaaaaaaye",
      "aaaaaaaayf",
      "aaaaaaaayg",
      "aaaaaaaayh",
      "aaaaaaaayi",
      "aaaaaaaayj",
      "aaaaaaaayk",
      "aaaaaaaayl",
      "aaaaaaaaym",
      "aaaaaaaayn",
      "aaaaaaaayo",
      "aaaaaaaayp",
      "aaaaaaaayq",
      "aaaaaaaayr",
      "aaaaaaaays",
      "aaaaaaaayt",
      "aaaaaaaayu",
      "aaaaaaaayv",
      "aaaaaaaayw",
      "aaaaaaaayx",
      "aaaaaaaayy",
      "aaaaaaaayz",
      "aaaaaaaaza",
      "aaaaaaaazb",
      "aaaaaaaazc",
      "aaaaaaaazd",
      "aaaaaaaaze",
      "aaaaaaaazf",
      "aaaaaaaazg",
      "aaaaaaaazh",
      "aaaaaaaazi",
      "aaaaaaaazj",
      "aaaaaaaazk",
      "aaaaaaaazl",
      "aaaaaaaazm",
      "aaaaaaaazn",
      "aaaaaaaazo",
      "aaaaaaaazp",
      "aaaaaaaazq",
      "aaaaaaaazr",
      "aaaaaaaazs",
      "aaaaaaaazt",
      "aaaaaaaazu",
      "aaaaaaaazv",
      "aaaaaaaazw",
      "aaaaaaaazx",
      "aaaaaaaazy",
      "aaaaaaaazz",
    ],
  ),
  [
    "aaaaaaaaaa",
    "aaaaaaaaab",
    "aaaaaaaaac",
    "aaaaaaaaad",
    "aaaaaaaaae",
    "aaaaaaaaaf",
    "aaaaaaaaag",
    "aaaaaaaaah",
    "aaaaaaaaai",
    "aaaaaaaaaj",
    "aaaaaaaaak",
    "aaaaaaaaal",
    "aaaaaaaaan",
    "aaaaaaaaao",
    "aaaaaaaaap",
    "aaaaaaaaaq",
    "aaaaaaaaar",
    "aaaaaaaaas",
    "aaaaaaaaat",
    "aaaaaaaaau",
    "aaaaaaaaav",
    "aaaaaaaaaw",
    "aaaaaaaaay",
    "aaaaaaaaaz",
    "aaaaaaaabc",
    "aaaaaaaabm",
    "aaaaaaaacb",
    "aaaaaaaacd",
    "aaaaaaaadc",
    "aaaaaaaade",
    "aaaaaaaaed",
    "aaaaaaaaef",
    "aaaaaaaafe",
    "aaaaaaaafg",
    "aaaaaaaagf",
    "aaaaaaaagh",
    "aaaaaaaahg",
    "aaaaaaaahi",
    "aaaaaaaaih",
    "aaaaaaaaij",
    "aaaaaaaaji",
    "aaaaaaaajk",
    "aaaaaaaakj",
    "aaaaaaaakl",
    "aaaaaaaalk",
    "aaaaaaaanm",
    "aaaaaaaano",
    "aaaaaaaaon",
    "aaaaaaaaop",
    "aaaaaaaapo",
    "aaaaaaaapq",
    "aaaaaaaaqp",
    "aaaaaaaaqr",
    "aaaaaaaarq",
    "aaaaaaaars",
    "aaaaaaaasr",
    "aaaaaaaast",
    "aaaaaaaats",
    "aaaaaaaatu",
    "aaaaaaaaut",
    "aaaaaaaauv",
    "aaaaaaaavu",
    "aaaaaaaavw",
    "aaaaaaaawv",
    "aaaaaaaawx",
    "aaaaaaaayx",
    "aaaaaaaayz",
    "aaaaaaaaza",
    "aaaaaaaazy",
  ],
)
